# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabs',
            fields=[
                ('cab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('status', models.BooleanField()),
                ('cab_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('stop_latitude', models.FloatField()),
                ('stop_longitude', models.FloatField()),
                ('cab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.Cabs')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.Customer')),
            ],
        ),
    ]
