# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabs',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
